CREATE TABLE IF NOT EXISTS groups (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  overseer VARCHAR(150) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS report_users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  group_id INT NOT NULL,
  name VARCHAR(150) NOT NULL,
  status ENUM('Pioneer', 'Aux Pioneer', 'Other') NOT NULL DEFAULT 'Other',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_report_users_group
    FOREIGN KEY (group_id) REFERENCES groups(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS monthly_reports (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  report_month CHAR(7) NOT NULL,
  hours DECIMAL(6,2) NOT NULL DEFAULT 0,
  bible_studies INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_user_month (user_id, report_month),
  CONSTRAINT fk_monthly_reports_user
    FOREIGN KEY (user_id) REFERENCES report_users(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
